import type { CompiledCabinet, HardwareUse } from "../panels";
import { umToMmRounded } from "../units";

/**
 * Assembly knowledge model (PRD §10). Steps come from an approved recipe and are
 * bound to the order's own panels and hardware quantities. Text is approved
 * template text, never generated by a language model.
 */

export interface AssemblyStep {
  id: string;
  order: number;
  title: string;
  titleZh: string;
  moduleIndex: number | null;
  panelIds: string[];
  hardware: HardwareUse[];
  tools: string[];
  instructions: string[];
  checks: string[];
  safety: string[];
  dependsOn: string[];
  /** Orientation hint for the 3D viewer, e.g. which face should be up. */
  orientation: string;
  isSafetyCritical: boolean;
}

export interface AssemblyGuide {
  recipeId: string;
  recipeVersion: number;
  estimatedMinutes: number;
  people: number;
  workspaceNote: string;
  tools: string[];
  steps: AssemblyStep[];
}

export const ASSEMBLY_RECIPE_LOW_01 = { id: "AR-LOW-01", version: 1 };

export function buildAssemblyGuide(cabinet: CompiledCabinet, tools: string[]): AssemblyGuide {
  const steps: AssemblyStep[] = [];
  let order = 0;
  const push = (s: Omit<AssemblyStep, "order">) => {
    order++;
    steps.push({ ...s, order });
  };
  const hwOf = (jointId: string): HardwareUse[] => cabinet.joints.find((j) => j.id === jointId)?.hardware ?? [];

  const lastStepOfModule: Record<number, string> = {};

  for (const m of cabinet.modules) {
    const M = `M${m.index}`;
    const sideL = `${M}-SIDE_L`;
    const sideR = `${M}-SIDE_R`;
    const bottom = `${M}-BOTTOM`;
    const back = `${M}-BACK`;
    const perModuleTop = cabinet.design.topPanelStyle === "per_module" ? `${M}-TOP` : null;
    let prev: string | null = null;
    const dep = () => (prev ? [prev] : []);

    push({
      id: `${M}-S1`,
      title: `Module ${m.index}: fit the adjustable feet`,
      titleZh: `模块 ${m.index}：安装可调柜脚`,
      moduleIndex: m.index,
      panelIds: [bottom],
      hardware: hwOf(`${M}-J-FEET`),
      tools: ["PH2 screwdriver"],
      instructions: [
        `Lay the bottom panel (${label(cabinet, bottom)}) on a blanket with the underside facing up. The underside has four small locating holes near the corners.`,
        "Place a foot over each locating hole and fix it with four foot screws.",
      ],
      checks: ["All four feet are tight and sit flat.", "No screw has broken through the top face."],
      safety: [],
      dependsOn: [],
      orientation: "bottom panel underside up",
      isSafetyCritical: false,
    });
    prev = `${M}-S1`;

    for (const [side, id] of [["left", sideL], ["right", sideR]] as const) {
      const stepId = side === "left" ? `${M}-S2` : `${M}-S3`;
      const sideCode = side === "left" ? "L" : "R";
      push({
        id: stepId,
        title: `Module ${m.index}: insert connectors into the ${side} side`,
        titleZh: `模块 ${m.index}：在${side === "left" ? "左" : "右"}侧板装入连接件`,
        moduleIndex: m.index,
        panelIds: [id],
        hardware: mergeUses([...hwOf(`${M}-J-${sideCode}-BOTTOM`), ...hwOf(`${M}-J-${sideCode}-TOP`)]),
        tools: [],
        instructions: [
          `Take the ${side} side (${label(cabinet, id)}). The inner face has rectangular pockets near the top and bottom ends.`,
          "Press a connector into every pocket with the screw pointing towards the panel end.",
        ],
        checks: ["Every pocket has a connector.", "Connectors are fully seated and do not rock."],
        safety: [],
        dependsOn: dep(),
        orientation: "side panel inner face up",
        isSafetyCritical: false,
      });
      prev = stepId;
    }

    push({
      id: `${M}-S4`,
      title: `Module ${m.index}: stand the sides on the bottom and lock`,
      titleZh: `模块 ${m.index}：将侧板立在底板上并锁紧`,
      moduleIndex: m.index,
      panelIds: [sideL, sideR, bottom],
      hardware: [],
      tools: ["4 mm hex key"],
      instructions: [
        "Turn the bottom panel feet-down. Stand the left side on the bottom panel so the connector screws meet the pilot holes on the bottom's top face.",
        "Tighten each connector clockwise until the joint closes. Repeat for the right side.",
        `The banded front edges of the sides and bottom must all face the same way. Interior width should read ${umToMmRounded(m.interior.width_um)} mm.`,
      ],
      checks: ["Both sides are square to the bottom.", "Front edges are flush."],
      safety: ["Support each side while tightening so it cannot fall."],
      dependsOn: dep(),
      orientation: "carcass upright",
      isSafetyCritical: false,
    });
    prev = `${M}-S4`;

    if (perModuleTop) {
      push({
        id: `${M}-S5`,
        title: `Module ${m.index}: fit the top panel`,
        titleZh: `模块 ${m.index}：安装顶板`,
        moduleIndex: m.index,
        panelIds: [perModuleTop],
        hardware: [],
        tools: ["4 mm hex key"],
        instructions: [
          `Place the top panel (${label(cabinet, perModuleTop)}) on the sides with the pilot holes facing down. The top overhangs the front by ${umToMmRounded(cabinet.dims.doorZone_um)} mm.`,
          "Tighten the connectors at the top of each side.",
        ],
        checks: ["The top sits flat with no gap at the sides."],
        safety: [],
        dependsOn: dep(),
        orientation: "carcass upright",
        isSafetyCritical: false,
      });
      prev = `${M}-S5`;
    }

    push({
      id: `${M}-S6`,
      title: `Module ${m.index}: fix the back panel`,
      titleZh: `模块 ${m.index}：固定背板`,
      moduleIndex: m.index,
      panelIds: [back],
      hardware: hwOf(`${M}-J-BACK`),
      tools: ["PH2 screwdriver"],
      instructions: [
        "Lay the carcass on its front. Place the back panel with the white face inwards and align it with the outer edges.",
        "Check the carcass is square by measuring both diagonals, then drive a screw through every pre-drilled hole.",
      ],
      checks: ["Diagonals are equal within 2 mm.", "All screws are in."],
      safety: [],
      dependsOn: dep(),
      orientation: "carcass face down",
      isSafetyCritical: false,
    });
    prev = `${M}-S6`;

    if (m.shelfPositions_um.length) {
      const shelfIds = m.panelIds.filter((id) => id.startsWith(`${M}-SHELF-`));
      push({
        id: `${M}-S7`,
        title: `Module ${m.index}: fit shelf pins and shelves`,
        titleZh: `模块 ${m.index}：安装层板销与层板`,
        moduleIndex: m.index,
        panelIds: shelfIds,
        hardware: hwOf(`${M}-J-SHELVES`),
        tools: [],
        instructions: [
          `Stand the module up. Counting rows from the bottom, push four pins into row ${m.shelfRows.join(", row ")} (two per side).`,
          "Rest each shelf on its pins with the banded edge to the front.",
        ],
        checks: ["Each shelf sits on four pins and does not rock."],
        safety: [],
        dependsOn: dep(),
        orientation: "carcass upright",
        isSafetyCritical: false,
      });
      prev = `${M}-S7`;
    }

    if (m.doors.length) {
      const doorIds = m.doors.map((d) => d.panelId);
      const hinges = m.doors.flatMap((d) => hwOf(`${M}-J-HINGE-${d.hingeSide}`));
      const handles = m.doors.flatMap((d) => hwOf(`${M}-J-HANDLE-${d.hingeSide}`));
      push({
        id: `${M}-S8`,
        title: `Module ${m.index}: mount hinges and hang the door${m.doors.length > 1 ? "s" : ""}`,
        titleZh: `模块 ${m.index}：安装铰链并挂门`,
        moduleIndex: m.index,
        panelIds: doorIds,
        hardware: mergeUses([...hinges, ...handles]),
        tools: ["PH2 screwdriver"],
        instructions: [
          "Press a hinge into each 35 mm cup on the back of the door and fix it with two screws.",
          `Screw a mounting plate to the side at each pair of hinge holes (${m.doors.map((d) => `${d.hingeCount} on the ${d.hingeSide === "L" ? "left" : "right"} side`).join(", ")}).`,
          "Clip the hinges onto the plates, then adjust until the door gap is even (2 mm).",
          ...(handles.length ? ["Fit the handle through the two pre-drilled holes from the front and tighten the screws from the back."] : []),
        ],
        checks: ["Door opens and closes freely without touching the top or neighbouring module."],
        safety: [],
        dependsOn: dep(),
        orientation: "carcass upright",
        isSafetyCritical: false,
      });
      prev = `${M}-S8`;
    }
    lastStepOfModule[m.index] = prev;
  }

  const moduleFinals = Object.values(lastStepOfModule);
  let rowPrev: string[] = moduleFinals;

  if (cabinet.modules.length > 1) {
    const joinJoints = cabinet.joints.filter((j) => j.kind === "inter_module_bolt");
    push({
      id: "ROW-S1",
      title: "Join the modules",
      titleZh: "连接各模块",
      moduleIndex: null,
      panelIds: joinJoints.flatMap((j) => j.panelIds),
      hardware: mergeUses(joinJoints.flatMap((j) => j.hardware)),
      tools: ["4 mm hex key"],
      instructions: [
        "Stand the modules side by side in order, fronts flush, on a level floor.",
        "Push a connecting bolt through each pair of aligned 8 mm holes in the neighbouring sides and tighten.",
      ],
      checks: ["Fronts and tops are flush across all modules."],
      safety: [],
      dependsOn: rowPrev,
      orientation: "modules upright",
      isSafetyCritical: false,
    });
    rowPrev = ["ROW-S1"];
  }

  if (cabinet.design.topPanelStyle === "single") {
    push({
      id: "ROW-S2",
      title: "Fit the spanning top panel",
      titleZh: "安装整块顶板",
      moduleIndex: null,
      panelIds: ["ROW-TOP"],
      hardware: [],
      tools: ["4 mm hex key"],
      instructions: [
        `Place the top panel (${label(cabinet, "ROW-TOP")}) with pilot holes facing down. It overhangs the front by ${umToMmRounded(cabinet.dims.doorZone_um)} mm and is flush at both ends.`,
        "Tighten the connectors at the top of every side.",
      ],
      checks: ["Top is flat and flush at the ends."],
      safety: [cabinet.dims.finished.width_um >= 1_500_000 ? "Two people should lift the top panel." : ""].filter(Boolean),
      dependsOn: rowPrev,
      orientation: "modules upright",
      isSafetyCritical: false,
    });
    rowPrev = ["ROW-S2"];
  }

  push({
    id: "ROW-S3",
    title: "Level the feet",
    titleZh: "调平柜脚",
    moduleIndex: null,
    panelIds: [],
    hardware: [],
    tools: ["Spirit level"],
    instructions: ["Turn the feet until the top reads level front to back and side to side. All feet must touch the floor."],
    checks: ["Doors stay where you leave them and gaps are even."],
    safety: [],
    dependsOn: rowPrev,
    orientation: "in final position",
    isSafetyCritical: false,
  });
  rowPrev = ["ROW-S3"];

  if (cabinet.antiTipRequired) {
    push({
      id: "ROW-S4",
      title: "Secure the cabinet to the wall",
      titleZh: "将柜体固定到墙面",
      moduleIndex: null,
      panelIds: [],
      hardware: hwOf("ROW-J-ANTI-TIP"),
      tools: ["Drill", "Fixings suitable for your wall type"],
      instructions: [
        "Attach the restraint bracket to the top rear edge of the cabinet using the supplied screws.",
        "Fix the wall bracket to a solid part of the wall (stud or masonry) using fixings suitable for your wall, then connect the two brackets.",
      ],
      checks: ["The cabinet cannot be tipped forward by pulling the top edge."],
      safety: [
        "This cabinet must be restrained to the wall. Wall fixings are not supplied because they depend on your wall type. If you are unsure of the wall structure, use a professional installer.",
      ],
      dependsOn: rowPrev,
      orientation: "in final position",
      isSafetyCritical: true,
    });
    rowPrev = ["ROW-S4"];
  }

  push({
    id: "ROW-S5",
    title: "Final checks",
    titleZh: "最终检查",
    moduleIndex: null,
    panelIds: [],
    hardware: [],
    tools: [],
    instructions: ["Check every connector is tight, every shelf sits on four pins and doors close cleanly.", "Keep the guide for future reference."],
    checks: ["No loose hardware left over except spares."],
    safety: [],
    dependsOn: rowPrev,
    orientation: "in final position",
    isSafetyCritical: false,
  });

  const minutes = 25 + cabinet.modules.length * 20 + cabinet.modules.filter((m) => m.doors.length).length * 10 + (cabinet.antiTipRequired ? 15 : 0);
  return {
    recipeId: ASSEMBLY_RECIPE_LOW_01.id,
    recipeVersion: ASSEMBLY_RECIPE_LOW_01.version,
    estimatedMinutes: minutes,
    people: cabinet.dims.finished.width_um >= 1_500_000 ? 2 : 1,
    workspaceNote: `Clear floor area of about ${umToMmRounded(cabinet.dims.finished.width_um) + 600} × ${umToMmRounded(cabinet.dims.finished.depth_um) + 1200} mm with a blanket to protect panel faces.`,
    tools,
    steps,
  };
}

/** Validates that the step graph is acyclic and every panel is used by at least one step. */
export function validateAssemblyGuide(guide: AssemblyGuide, cabinet: CompiledCabinet): { ok: boolean; problems: string[] } {
  const problems: string[] = [];
  const ids = new Set(guide.steps.map((s) => s.id));
  for (const s of guide.steps) {
    for (const d of s.dependsOn) if (!ids.has(d)) problems.push(`Step ${s.id} depends on unknown step ${d}`);
  }
  const state = new Map<string, number>();
  const byId = new Map(guide.steps.map((s) => [s.id, s]));
  const visit = (id: string, stack: string[]): void => {
    const st = state.get(id) ?? 0;
    if (st === 1) {
      problems.push(`Cycle detected: ${[...stack, id].join(" -> ")}`);
      return;
    }
    if (st === 2) return;
    state.set(id, 1);
    for (const d of byId.get(id)?.dependsOn ?? []) visit(d, [...stack, id]);
    state.set(id, 2);
  };
  for (const s of guide.steps) visit(s.id, []);
  const covered = new Set(guide.steps.flatMap((s) => s.panelIds));
  for (const p of cabinet.panels) if (!covered.has(p.id)) problems.push(`Panel ${p.id} is not used in any assembly step`);
  return { ok: problems.length === 0, problems };
}

function label(cabinet: CompiledCabinet, panelId: string): string {
  return cabinet.panels.find((p) => p.id === panelId)?.label ?? panelId;
}

function mergeUses(uses: HardwareUse[]): HardwareUse[] {
  const map = new Map<string, number>();
  for (const u of uses) map.set(u.sku, (map.get(u.sku) ?? 0) + u.qty);
  return [...map.entries()].map(([sku, qty]) => ({ sku, qty }));
}
